twilio:
  accountId: 
  accountToken:
  number:

# Optional. If specified, Nexmo will be used for non-US SMS and 
# voice verification.
nexmo:
  apiKey:
  apiSecret:
  number:

gcm:
  apiKey: 

# Optional. Only if iOS clients are supported.
apn:
  # In PEM format.
  certificate: 
  
  # In PEM format.
  key: 

s3:
  accessKey: 
  accessSecret: 

  # Name of the S3 bucket (needs to have been created)
  # for attachments to go.  Should be configured with
  # correct permissions.
  attachmentsBucket:

memcache:
  servers: 
  user: 
  password: 

redis:
  url: 

federation:
  name:
  peers: 
    -
      name: somepeer
      url: https://foo.com
      authenticationToken: foo
      certificate: in pem format 

# Optional address of graphite server to report metrics
graphite:
  host:
  port:

http:
  shutdownGracePeriod: 0s

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: 

  # the password
  password: 

  # the JDBC URL
  url: jdbc:postgresql://somehost:somport/somedb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute
